spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect

springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.path: /docs/swagger-ui.html

management:
  endpoints:
    web:
      exposure.include: prometheus